#!/bin/bash
echo "3333 Port will be opened for Debugging........"
echo "Opening Openocd Port........"
openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f1x.cfg


